// This file was generated by RedwoodJS
import { Success } from './PostsCell'
import type { CellProps } from '@redwoodjs/web'
import type { POSTS, POSTSVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './PostsCell'

type CellInputs = CellProps<SuccessType, POSTS, POSTSVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
