// This file was generated by RedwoodJS
import { Success } from './ArticleCell'
import type { CellProps } from '@redwoodjs/web'
import type { ArticleQuery, ArticleQueryVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './ArticleCell'

type CellInputs = CellProps<SuccessType, ArticleQuery, ArticleQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
