// This file was generated by RedwoodJS
import AboutPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/AboutPage/AboutPage'
import ArticlePageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/ArticlePage/ArticlePage'
import ContactPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/ContactPage/ContactPage'
import FatalErrorPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/FatalErrorPage/FatalErrorPage'
import ForgotPasswordPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/ForgotPasswordPage/ForgotPasswordPage'
import HomePageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/HomePage/HomePage'
import LoginPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/LoginPage/LoginPage'
import NotFoundPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/NotFoundPage/NotFoundPage'
import PricingPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/PricingPage/PricingPage'
import ResetPasswordPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/ResetPasswordPage/ResetPasswordPage'
import SignupPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/SignupPage/SignupPage'
import PostEditPostPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/Post/EditPostPage/EditPostPage'
import PostNewPostPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/Post/NewPostPage/NewPostPage'
import PostPostPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/Post/PostPage/PostPage'
import PostPostsPageType from '/Users/hsk/Documents/Code/Github/Napna-General-1/web/src/pages/Post/PostsPage/PostsPage'

declare global {
  const AboutPage: typeof AboutPageType
  const ArticlePage: typeof ArticlePageType
  const ContactPage: typeof ContactPageType
  const FatalErrorPage: typeof FatalErrorPageType
  const ForgotPasswordPage: typeof ForgotPasswordPageType
  const HomePage: typeof HomePageType
  const LoginPage: typeof LoginPageType
  const NotFoundPage: typeof NotFoundPageType
  const PricingPage: typeof PricingPageType
  const ResetPasswordPage: typeof ResetPasswordPageType
  const SignupPage: typeof SignupPageType
  const PostEditPostPage: typeof PostEditPostPageType
  const PostNewPostPage: typeof PostNewPostPageType
  const PostPostPage: typeof PostPostPageType
  const PostPostsPage: typeof PostPostsPageType
}
