// This file was generated by RedwoodJS
import FailurePageType from '/Users/hossamsulleman/Documents/GitHub/Napna-General/web/src/pages/FailurePage/FailurePage'
import FatalErrorPageType from '/Users/hossamsulleman/Documents/GitHub/Napna-General/web/src/pages/FatalErrorPage/FatalErrorPage'
import ForgotPasswordPageType from '/Users/hossamsulleman/Documents/GitHub/Napna-General/web/src/pages/ForgotPasswordPage/ForgotPasswordPage'
import HomePageType from '/Users/hossamsulleman/Documents/GitHub/Napna-General/web/src/pages/HomePage/HomePage'
import LoginPageType from '/Users/hossamsulleman/Documents/GitHub/Napna-General/web/src/pages/LoginPage/LoginPage'
import NotFoundPageType from '/Users/hossamsulleman/Documents/GitHub/Napna-General/web/src/pages/NotFoundPage/NotFoundPage'
import ResetPasswordPageType from '/Users/hossamsulleman/Documents/GitHub/Napna-General/web/src/pages/ResetPasswordPage/ResetPasswordPage'
import SignupPageType from '/Users/hossamsulleman/Documents/GitHub/Napna-General/web/src/pages/SignupPage/SignupPage'
import SuccessPageType from '/Users/hossamsulleman/Documents/GitHub/Napna-General/web/src/pages/SuccessPage/SuccessPage'

declare global {
  const FailurePage: typeof FailurePageType
  const FatalErrorPage: typeof FatalErrorPageType
  const ForgotPasswordPage: typeof ForgotPasswordPageType
  const HomePage: typeof HomePageType
  const LoginPage: typeof LoginPageType
  const NotFoundPage: typeof NotFoundPageType
  const ResetPasswordPage: typeof ResetPasswordPageType
  const SignupPage: typeof SignupPageType
  const SuccessPage: typeof SuccessPageType
}
