// This file was generated by RedwoodJS
import * as Cell from './ProductsCell'
import type { CellProps } from '@redwoodjs/web'
import type { Products, ProductsVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './ProductsCell'

type CellInputs = CellProps<SuccessType, Products, typeof Cell, ProductsVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
