// This file was generated by RedwoodJS
import * as Cell from './CheckoutSuccessCell'
import type { CellProps } from '@redwoodjs/web'
import type { getSuccessQuery, getSuccessQueryVariables } from 'types/graphql'

type SuccessType = typeof Cell.Success

export * from './CheckoutSuccessCell'

type CellInputs = CellProps<SuccessType, getSuccessQuery, typeof Cell, getSuccessQueryVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
