// This file was generated by RedwoodJS
import { Success } from './EditPostCell'
import type { CellProps } from '@redwoodjs/web'
import type { FindPostById, FindPostByIdVariables } from 'types/graphql'

type SuccessType = typeof Success

export * from './EditPostCell'

type CellInputs = CellProps<SuccessType, FindPostById, FindPostByIdVariables>

export default function (props: CellInputs): ReturnType<SuccessType>
